iters=10000;
fval_his=zeros(iters,2);
x_his=zeros(iters,144);
parfor i=1:1:iters
   t=i/100;
    x0=ones(1,144)*t; 
    options = optimoptions('fmincon');
    options = optimoptions(options,...
        'ConstraintTolerance',1e-10,...
        'Display', 'none',...
        'FiniteDifferenceType','central',...
        'FunctionTolerance',1e-10,...
        'MaxFunctionEvaluations',2e5,...  
        'MaxIterations', 2000,...
        'ObjectiveLimit',-1e100,...
        'OptimalityTolerance',1e-10,...
        'StepTolerance',1e-500,...
        'UseParallel',false,...
        'Algorithm', 'interior-point',...
        'TolConSQP',1e-100);
    [x,fval,exitflag,output] = fmincon(@ObjectFunction,x0,Aineq,bineq,Aeq,beq,lb,ub,[],options);
    fprintf('%d,%d\n',t,fval);
    fval_his(i,:)=[i,fval];
    x_his(i,:)=x;
end